@startuml
allow_mixing
package "DTO"{
            json "UsuarioStoreReq" as userloginreq {
                "nome" : "",
                "email" : "",
                "senha" : "",
                "avalicoes":[{ 
                    "data": "",
                    "avalicao":"",
                    "exercico" :""
            }]
            }

            json "UsuarioRes" as userloginres {
                "msgcode" : "001",
                "userobject": "{}"
            }
            json "UsuarioAdicionaAvalicaoReq" as UsuarioStoreq{
                "id" : "",
                "avalicoes":[{ 
                    "data": " ",
                    "avalicao":"",
                    "exercico" :""
            }]
                
            }
            json "UsusarioStoreRes" as usercreateres{
                "msgcode" : "002",
                "userobject": "{}"
            }

        }
