@startuml
allow_mixing
package "DTO"{

        package "UsuarioDTO"{
            json "UsuarioStoreReq" as userloginreq {
                "nome" : "",
                "email" : "",
                "senha" : "",
                "avalicoes":[{ 
                    "data": "",
                    "avalicao":"",
                    "exercico" :""
                }]
            }
            json "UsuarioStoreRes" as userloginres {
                "StatusCode" : "",
                "msg" : ""
            }
        
            json "UsuarioBuscarFichasReq" as UsuarioBuscarFichasReq {
                "id" : ""
            }
            json "UsuarioBuscarFichasRes" as UsuarioBuscarFichasRes{
                "fichaDeTreinamento" : [{ 
                    "id" : "",    
                    "nivel" : "",
                    "frequncia" : "",
                    "avaliacaoPosTreino" : "",
                    "dataInicialDaFicha" : "",
                    "gruposMusculares": "",
                    "exercicios" : "",
                    "Usuario" : "" 

                }]                 
            }
        }
        package "FichaDeTreinamento"{
            json "FichaDeTreinamentoStoreReq" as FichaDeTreinamentoStoreReq {
                "nivel" : "",
                "frequncia" : "",
                "avaliacaoPosTreino" : "",
                "dataInicialDaFicha" : "",
                "gruposMusculares": "",
                "exercicios" : "",
                "Usuario" : "" 
            }
            json "FichaDeTreinamentoStoreRes" as FichaDeTreinamentoStoreRes {
                "StatusCode" : "",
                "msg" : ""
            }
            json "FichaDeTreinamentoDestroyReq" as FichaDeTreinamentoDestroyReq {
                "id" : ""
            }
            json "FichaDeTreinamentoDestroyRes" as FichaDeTreinamentoDestroyRes { 
                "id" : "",    
                "nivel" : "",
                "frequncia" : "",
                "avaliacaoPosTreino" : "",
                "dataInicialDaFicha" : "",
                "gruposMusculares": "",
                "exercicios" : "",
                "Usuario" : "" 
                                 
            }
            json "FichaDeTreinamentoExercicioReq" as FichaDeTreinamentoAddExercicioReq {
                "id" : "",
                "idExercicio" : ""
            }
            json "FichaDeTreinamentoExercicioRes" as FichaDeTreinamentoAddExercicioRes {
                "FichaDeTreinamento": [{
                    "exercicio" : ""
                }]
            }

        }
        package "Exercicio"{
            json "ExercicioStoreReq" as ExercicioStoreReq {
                "nome": "",  
	            "cargas": [{
                    "data": "",
                    "peso" : ""
                }],
                "avaliacoes": [{
                    "data": "",
                    "avaliacao": ""
                }],
                "gruposMusculares": [],
                "usuario": ""

            }
            json "ExercicioStoreRes" as ExercicioStoreRes {
                "StatusCode" : "",
                "msg" : ""
            }
            json "ExercicioDestroyReq" as ExercicioDestroyReq {
                "id" : ""
            }
            json "ExercicioDestroyRes" as ExercicioDestroyRes { 
                "id" : "",    
                "nome": "",  
                "cargas": [{
                    "data": "",
                    "peso" : ""
                }],
                "avaliacoes": [{
                    "data": "",
                    "avaliacao": ""
                }],
                "gruposMusculares": [],
                "usuario": ""
            }
            json "ExercicioAvaliacaoReq" as ExercicioAvaliacaoReq {
                "id" : "",
                "data" : "",
                "avaliacao" : ""
            }
            json "ExercicioAvaliacaoRes" as ExercicioAvaliacaoRes { 
                "id" : "",    
                "nome": "",  
                "avaliacoes": [{
                    "data": "",
                    "avaliacao": ""
                }],
                "usuario": ""
            }
            json "ExercicioCargaReq" as ExercicioCargaReq {
                "id" : "",
                "data" : "",
                "peso" : ""
            }
            json "ExercicioCargaRes" as ExercicioCargaRes { 
                "id" : "",    
                "nome": "",  
                "cargas": [{
                    "data": "",
                    "peso" : ""
                }],
                "usuario": ""
            }

  
  }
          
        
            
            

}